INCLUDE <p16f887.inc>
  
 ; CONFIG1
; __config 0x3FE4
 __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
; CONFIG2
; __config 0x3FFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
 
CBLOCK 0x70
CONT
AUX
ENDC
 
ORG 0x0

SETUP
;JUSTIFICADO Y REFERENCIAS
BANKSEL ADCON1 ;
MOVLW B'00000000' ;right justify
MOVWF ADCON1 ;Vdd and Vss as Vref
;CONFIGURACION DE E/S
BANKSEL TRISA;
BSF TRISA,0 ;Set RA0 to input
BCF TRISC,6
CLRF TRISD
BANKSEL STATUS
CLRF PORTA
CLRF PORTC
CLRF PORTD
BANKSEL ANSEL
BSF ANSEL,0 ;Set RA0 to analog
;CONFIGURACION INTERRUPCION POR RB0
;BANKSEL WPUB
;BSF WPUB,0
 
    ; Configuración de UART
    BANKSEL SPBRG
    MOVLW .25        ; Baud rate de 9600 a 4MHz
    MOVWF SPBRG
    BANKSEL TXSTA
    BSF TXSTA, TXEN     ; Activar transmisión
    BSF TXSTA, BRGH     ; Alta velocidad
    BANKSEL RCSTA
    BSF RCSTA, SPEN     ; Activar puerto serial
 
;CONFIGURACION ADC
BANKSEL ADCON0
MOVLW B'11000001' ;ADC Frc clock, OSC INTERNO, RA0, ENABLE=ON
MOVWF ADCON0 ;AN0, On
    
ADC_TEST:
;TIEMPO ADQUISICION
CALL SampleTime ;Acquisiton delay
;EMPEZAR CONVERSION
BANKSEL ADCON0
BSF ADCON0,GO ;Start conversion
;TESTEAR FINAL CONVERSION
BTFSC ADCON0,GO ;Is conversion done?
GOTO $-1 ;No, test again
;MOVER RESULTADOS A REGISTROS
BANKSEL ADRESH ;
MOVF ADRESH,W
BANKSEL PORTD
MOVWF PORTD
;MOVWF AUX
;BCF STATUS,C
;RRF AUX,F
;BCF STATUS,C
;RRF AUX,W  
BANKSEL TXREG
MOVWF TXREG         ; Cargar byte a transmitir
WAIT_TX:
BTFSS PIR1, TXIF    ; Esperar a que se complete la transmisión
GOTO WAIT_TX
GOTO ADC_TEST
    
SampleTime:
    
    	MOVLW	.256
	MOVWF	CONT
	LOOP
	DECFSZ	CONT,F
	GOTO	LOOP
	RETURN

END
